/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardOrganizationSlugRouteImport } from './routes/dashboard.$organizationSlug'
import { Route as DashboardOrganizationSlugIndexRouteImport } from './routes/dashboard.$organizationSlug.index'
import { Route as DashboardOrganizationSlugWebhooksRouteImport } from './routes/dashboard.$organizationSlug.webhooks'
import { Route as DashboardOrganizationSlugUsersRouteImport } from './routes/dashboard.$organizationSlug.users'
import { Route as DashboardOrganizationSlugSettingsRouteImport } from './routes/dashboard.$organizationSlug.settings'
import { Route as DashboardOrganizationSlugRolesRouteImport } from './routes/dashboard.$organizationSlug.roles'
import { Route as DashboardOrganizationSlugNewslettersRouteImport } from './routes/dashboard.$organizationSlug.newsletters'
import { Route as DashboardOrganizationSlugLogsRouteImport } from './routes/dashboard.$organizationSlug.logs'
import { Route as DashboardOrganizationSlugInboxRouteImport } from './routes/dashboard.$organizationSlug.inbox'
import { Route as DashboardOrganizationSlugGroupsRouteImport } from './routes/dashboard.$organizationSlug.groups'
import { Route as DashboardOrganizationSlugFlowsRouteImport } from './routes/dashboard.$organizationSlug.flows'
import { Route as DashboardOrganizationSlugDevicesRouteImport } from './routes/dashboard.$organizationSlug.devices'
import { Route as DashboardOrganizationSlugContactsRouteImport } from './routes/dashboard.$organizationSlug.contacts'
import { Route as DashboardOrganizationSlugAuditRouteImport } from './routes/dashboard.$organizationSlug.audit'
import { Route as DashboardOrganizationSlugAccountRouteImport } from './routes/dashboard.$organizationSlug.account'
import { Route as DashboardOrganizationSlugFlowsIndexRouteImport } from './routes/dashboard.$organizationSlug.flows.index'
import { Route as DashboardOrganizationSlugFlowsNewRouteImport } from './routes/dashboard.$organizationSlug.flows.new'
import { Route as DashboardOrganizationSlugFlowsFlowIdRouteImport } from './routes/dashboard.$organizationSlug.flows.$flowId'
import { Route as DashboardOrganizationSlugDevicesIdRouteImport } from './routes/dashboard.$organizationSlug.devices.$id'
import { Route as DashboardOrganizationSlugFlowsFlowIdSessionsRouteImport } from './routes/dashboard.$organizationSlug.flows.$flowId.sessions'
import { Route as DashboardOrganizationSlugFlowsFlowIdLogsRouteImport } from './routes/dashboard.$organizationSlug.flows.$flowId.logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationSlugRoute =
  DashboardOrganizationSlugRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganizationSlugIndexRoute =
  DashboardOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugWebhooksRoute =
  DashboardOrganizationSlugWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugUsersRoute =
  DashboardOrganizationSlugUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugSettingsRoute =
  DashboardOrganizationSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugRolesRoute =
  DashboardOrganizationSlugRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugNewslettersRoute =
  DashboardOrganizationSlugNewslettersRouteImport.update({
    id: '/newsletters',
    path: '/newsletters',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugLogsRoute =
  DashboardOrganizationSlugLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugInboxRoute =
  DashboardOrganizationSlugInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugGroupsRoute =
  DashboardOrganizationSlugGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugFlowsRoute =
  DashboardOrganizationSlugFlowsRouteImport.update({
    id: '/flows',
    path: '/flows',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugDevicesRoute =
  DashboardOrganizationSlugDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugContactsRoute =
  DashboardOrganizationSlugContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugAuditRoute =
  DashboardOrganizationSlugAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugAccountRoute =
  DashboardOrganizationSlugAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardOrganizationSlugRoute,
  } as any)
const DashboardOrganizationSlugFlowsIndexRoute =
  DashboardOrganizationSlugFlowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationSlugFlowsRoute,
  } as any)
const DashboardOrganizationSlugFlowsNewRoute =
  DashboardOrganizationSlugFlowsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardOrganizationSlugFlowsRoute,
  } as any)
const DashboardOrganizationSlugFlowsFlowIdRoute =
  DashboardOrganizationSlugFlowsFlowIdRouteImport.update({
    id: '/$flowId',
    path: '/$flowId',
    getParentRoute: () => DashboardOrganizationSlugFlowsRoute,
  } as any)
const DashboardOrganizationSlugDevicesIdRoute =
  DashboardOrganizationSlugDevicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardOrganizationSlugDevicesRoute,
  } as any)
const DashboardOrganizationSlugFlowsFlowIdSessionsRoute =
  DashboardOrganizationSlugFlowsFlowIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => DashboardOrganizationSlugFlowsFlowIdRoute,
  } as any)
const DashboardOrganizationSlugFlowsFlowIdLogsRoute =
  DashboardOrganizationSlugFlowsFlowIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DashboardOrganizationSlugFlowsFlowIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/$organizationSlug': typeof DashboardOrganizationSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$organizationSlug/account': typeof DashboardOrganizationSlugAccountRoute
  '/dashboard/$organizationSlug/audit': typeof DashboardOrganizationSlugAuditRoute
  '/dashboard/$organizationSlug/contacts': typeof DashboardOrganizationSlugContactsRoute
  '/dashboard/$organizationSlug/devices': typeof DashboardOrganizationSlugDevicesRouteWithChildren
  '/dashboard/$organizationSlug/flows': typeof DashboardOrganizationSlugFlowsRouteWithChildren
  '/dashboard/$organizationSlug/groups': typeof DashboardOrganizationSlugGroupsRoute
  '/dashboard/$organizationSlug/inbox': typeof DashboardOrganizationSlugInboxRoute
  '/dashboard/$organizationSlug/logs': typeof DashboardOrganizationSlugLogsRoute
  '/dashboard/$organizationSlug/newsletters': typeof DashboardOrganizationSlugNewslettersRoute
  '/dashboard/$organizationSlug/roles': typeof DashboardOrganizationSlugRolesRoute
  '/dashboard/$organizationSlug/settings': typeof DashboardOrganizationSlugSettingsRoute
  '/dashboard/$organizationSlug/users': typeof DashboardOrganizationSlugUsersRoute
  '/dashboard/$organizationSlug/webhooks': typeof DashboardOrganizationSlugWebhooksRoute
  '/dashboard/$organizationSlug/': typeof DashboardOrganizationSlugIndexRoute
  '/dashboard/$organizationSlug/devices/$id': typeof DashboardOrganizationSlugDevicesIdRoute
  '/dashboard/$organizationSlug/flows/$flowId': typeof DashboardOrganizationSlugFlowsFlowIdRouteWithChildren
  '/dashboard/$organizationSlug/flows/new': typeof DashboardOrganizationSlugFlowsNewRoute
  '/dashboard/$organizationSlug/flows/': typeof DashboardOrganizationSlugFlowsIndexRoute
  '/dashboard/$organizationSlug/flows/$flowId/logs': typeof DashboardOrganizationSlugFlowsFlowIdLogsRoute
  '/dashboard/$organizationSlug/flows/$flowId/sessions': typeof DashboardOrganizationSlugFlowsFlowIdSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$organizationSlug/account': typeof DashboardOrganizationSlugAccountRoute
  '/dashboard/$organizationSlug/audit': typeof DashboardOrganizationSlugAuditRoute
  '/dashboard/$organizationSlug/contacts': typeof DashboardOrganizationSlugContactsRoute
  '/dashboard/$organizationSlug/devices': typeof DashboardOrganizationSlugDevicesRouteWithChildren
  '/dashboard/$organizationSlug/groups': typeof DashboardOrganizationSlugGroupsRoute
  '/dashboard/$organizationSlug/inbox': typeof DashboardOrganizationSlugInboxRoute
  '/dashboard/$organizationSlug/logs': typeof DashboardOrganizationSlugLogsRoute
  '/dashboard/$organizationSlug/newsletters': typeof DashboardOrganizationSlugNewslettersRoute
  '/dashboard/$organizationSlug/roles': typeof DashboardOrganizationSlugRolesRoute
  '/dashboard/$organizationSlug/settings': typeof DashboardOrganizationSlugSettingsRoute
  '/dashboard/$organizationSlug/users': typeof DashboardOrganizationSlugUsersRoute
  '/dashboard/$organizationSlug/webhooks': typeof DashboardOrganizationSlugWebhooksRoute
  '/dashboard/$organizationSlug': typeof DashboardOrganizationSlugIndexRoute
  '/dashboard/$organizationSlug/devices/$id': typeof DashboardOrganizationSlugDevicesIdRoute
  '/dashboard/$organizationSlug/flows/$flowId': typeof DashboardOrganizationSlugFlowsFlowIdRouteWithChildren
  '/dashboard/$organizationSlug/flows/new': typeof DashboardOrganizationSlugFlowsNewRoute
  '/dashboard/$organizationSlug/flows': typeof DashboardOrganizationSlugFlowsIndexRoute
  '/dashboard/$organizationSlug/flows/$flowId/logs': typeof DashboardOrganizationSlugFlowsFlowIdLogsRoute
  '/dashboard/$organizationSlug/flows/$flowId/sessions': typeof DashboardOrganizationSlugFlowsFlowIdSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/$organizationSlug': typeof DashboardOrganizationSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$organizationSlug/account': typeof DashboardOrganizationSlugAccountRoute
  '/dashboard/$organizationSlug/audit': typeof DashboardOrganizationSlugAuditRoute
  '/dashboard/$organizationSlug/contacts': typeof DashboardOrganizationSlugContactsRoute
  '/dashboard/$organizationSlug/devices': typeof DashboardOrganizationSlugDevicesRouteWithChildren
  '/dashboard/$organizationSlug/flows': typeof DashboardOrganizationSlugFlowsRouteWithChildren
  '/dashboard/$organizationSlug/groups': typeof DashboardOrganizationSlugGroupsRoute
  '/dashboard/$organizationSlug/inbox': typeof DashboardOrganizationSlugInboxRoute
  '/dashboard/$organizationSlug/logs': typeof DashboardOrganizationSlugLogsRoute
  '/dashboard/$organizationSlug/newsletters': typeof DashboardOrganizationSlugNewslettersRoute
  '/dashboard/$organizationSlug/roles': typeof DashboardOrganizationSlugRolesRoute
  '/dashboard/$organizationSlug/settings': typeof DashboardOrganizationSlugSettingsRoute
  '/dashboard/$organizationSlug/users': typeof DashboardOrganizationSlugUsersRoute
  '/dashboard/$organizationSlug/webhooks': typeof DashboardOrganizationSlugWebhooksRoute
  '/dashboard/$organizationSlug/': typeof DashboardOrganizationSlugIndexRoute
  '/dashboard/$organizationSlug/devices/$id': typeof DashboardOrganizationSlugDevicesIdRoute
  '/dashboard/$organizationSlug/flows/$flowId': typeof DashboardOrganizationSlugFlowsFlowIdRouteWithChildren
  '/dashboard/$organizationSlug/flows/new': typeof DashboardOrganizationSlugFlowsNewRoute
  '/dashboard/$organizationSlug/flows/': typeof DashboardOrganizationSlugFlowsIndexRoute
  '/dashboard/$organizationSlug/flows/$flowId/logs': typeof DashboardOrganizationSlugFlowsFlowIdLogsRoute
  '/dashboard/$organizationSlug/flows/$flowId/sessions': typeof DashboardOrganizationSlugFlowsFlowIdSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/$organizationSlug'
    | '/dashboard/'
    | '/dashboard/$organizationSlug/account'
    | '/dashboard/$organizationSlug/audit'
    | '/dashboard/$organizationSlug/contacts'
    | '/dashboard/$organizationSlug/devices'
    | '/dashboard/$organizationSlug/flows'
    | '/dashboard/$organizationSlug/groups'
    | '/dashboard/$organizationSlug/inbox'
    | '/dashboard/$organizationSlug/logs'
    | '/dashboard/$organizationSlug/newsletters'
    | '/dashboard/$organizationSlug/roles'
    | '/dashboard/$organizationSlug/settings'
    | '/dashboard/$organizationSlug/users'
    | '/dashboard/$organizationSlug/webhooks'
    | '/dashboard/$organizationSlug/'
    | '/dashboard/$organizationSlug/devices/$id'
    | '/dashboard/$organizationSlug/flows/$flowId'
    | '/dashboard/$organizationSlug/flows/new'
    | '/dashboard/$organizationSlug/flows/'
    | '/dashboard/$organizationSlug/flows/$flowId/logs'
    | '/dashboard/$organizationSlug/flows/$flowId/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/$organizationSlug/account'
    | '/dashboard/$organizationSlug/audit'
    | '/dashboard/$organizationSlug/contacts'
    | '/dashboard/$organizationSlug/devices'
    | '/dashboard/$organizationSlug/groups'
    | '/dashboard/$organizationSlug/inbox'
    | '/dashboard/$organizationSlug/logs'
    | '/dashboard/$organizationSlug/newsletters'
    | '/dashboard/$organizationSlug/roles'
    | '/dashboard/$organizationSlug/settings'
    | '/dashboard/$organizationSlug/users'
    | '/dashboard/$organizationSlug/webhooks'
    | '/dashboard/$organizationSlug'
    | '/dashboard/$organizationSlug/devices/$id'
    | '/dashboard/$organizationSlug/flows/$flowId'
    | '/dashboard/$organizationSlug/flows/new'
    | '/dashboard/$organizationSlug/flows'
    | '/dashboard/$organizationSlug/flows/$flowId/logs'
    | '/dashboard/$organizationSlug/flows/$flowId/sessions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/$organizationSlug'
    | '/dashboard/'
    | '/dashboard/$organizationSlug/account'
    | '/dashboard/$organizationSlug/audit'
    | '/dashboard/$organizationSlug/contacts'
    | '/dashboard/$organizationSlug/devices'
    | '/dashboard/$organizationSlug/flows'
    | '/dashboard/$organizationSlug/groups'
    | '/dashboard/$organizationSlug/inbox'
    | '/dashboard/$organizationSlug/logs'
    | '/dashboard/$organizationSlug/newsletters'
    | '/dashboard/$organizationSlug/roles'
    | '/dashboard/$organizationSlug/settings'
    | '/dashboard/$organizationSlug/users'
    | '/dashboard/$organizationSlug/webhooks'
    | '/dashboard/$organizationSlug/'
    | '/dashboard/$organizationSlug/devices/$id'
    | '/dashboard/$organizationSlug/flows/$flowId'
    | '/dashboard/$organizationSlug/flows/new'
    | '/dashboard/$organizationSlug/flows/'
    | '/dashboard/$organizationSlug/flows/$flowId/logs'
    | '/dashboard/$organizationSlug/flows/$flowId/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$organizationSlug': {
      id: '/dashboard/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/dashboard/$organizationSlug'
      preLoaderRoute: typeof DashboardOrganizationSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$organizationSlug/': {
      id: '/dashboard/$organizationSlug/'
      path: '/'
      fullPath: '/dashboard/$organizationSlug/'
      preLoaderRoute: typeof DashboardOrganizationSlugIndexRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/webhooks': {
      id: '/dashboard/$organizationSlug/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/$organizationSlug/webhooks'
      preLoaderRoute: typeof DashboardOrganizationSlugWebhooksRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/users': {
      id: '/dashboard/$organizationSlug/users'
      path: '/users'
      fullPath: '/dashboard/$organizationSlug/users'
      preLoaderRoute: typeof DashboardOrganizationSlugUsersRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/settings': {
      id: '/dashboard/$organizationSlug/settings'
      path: '/settings'
      fullPath: '/dashboard/$organizationSlug/settings'
      preLoaderRoute: typeof DashboardOrganizationSlugSettingsRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/roles': {
      id: '/dashboard/$organizationSlug/roles'
      path: '/roles'
      fullPath: '/dashboard/$organizationSlug/roles'
      preLoaderRoute: typeof DashboardOrganizationSlugRolesRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/newsletters': {
      id: '/dashboard/$organizationSlug/newsletters'
      path: '/newsletters'
      fullPath: '/dashboard/$organizationSlug/newsletters'
      preLoaderRoute: typeof DashboardOrganizationSlugNewslettersRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/logs': {
      id: '/dashboard/$organizationSlug/logs'
      path: '/logs'
      fullPath: '/dashboard/$organizationSlug/logs'
      preLoaderRoute: typeof DashboardOrganizationSlugLogsRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/inbox': {
      id: '/dashboard/$organizationSlug/inbox'
      path: '/inbox'
      fullPath: '/dashboard/$organizationSlug/inbox'
      preLoaderRoute: typeof DashboardOrganizationSlugInboxRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/groups': {
      id: '/dashboard/$organizationSlug/groups'
      path: '/groups'
      fullPath: '/dashboard/$organizationSlug/groups'
      preLoaderRoute: typeof DashboardOrganizationSlugGroupsRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/flows': {
      id: '/dashboard/$organizationSlug/flows'
      path: '/flows'
      fullPath: '/dashboard/$organizationSlug/flows'
      preLoaderRoute: typeof DashboardOrganizationSlugFlowsRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/devices': {
      id: '/dashboard/$organizationSlug/devices'
      path: '/devices'
      fullPath: '/dashboard/$organizationSlug/devices'
      preLoaderRoute: typeof DashboardOrganizationSlugDevicesRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/contacts': {
      id: '/dashboard/$organizationSlug/contacts'
      path: '/contacts'
      fullPath: '/dashboard/$organizationSlug/contacts'
      preLoaderRoute: typeof DashboardOrganizationSlugContactsRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/audit': {
      id: '/dashboard/$organizationSlug/audit'
      path: '/audit'
      fullPath: '/dashboard/$organizationSlug/audit'
      preLoaderRoute: typeof DashboardOrganizationSlugAuditRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/account': {
      id: '/dashboard/$organizationSlug/account'
      path: '/account'
      fullPath: '/dashboard/$organizationSlug/account'
      preLoaderRoute: typeof DashboardOrganizationSlugAccountRouteImport
      parentRoute: typeof DashboardOrganizationSlugRoute
    }
    '/dashboard/$organizationSlug/flows/': {
      id: '/dashboard/$organizationSlug/flows/'
      path: '/'
      fullPath: '/dashboard/$organizationSlug/flows/'
      preLoaderRoute: typeof DashboardOrganizationSlugFlowsIndexRouteImport
      parentRoute: typeof DashboardOrganizationSlugFlowsRoute
    }
    '/dashboard/$organizationSlug/flows/new': {
      id: '/dashboard/$organizationSlug/flows/new'
      path: '/new'
      fullPath: '/dashboard/$organizationSlug/flows/new'
      preLoaderRoute: typeof DashboardOrganizationSlugFlowsNewRouteImport
      parentRoute: typeof DashboardOrganizationSlugFlowsRoute
    }
    '/dashboard/$organizationSlug/flows/$flowId': {
      id: '/dashboard/$organizationSlug/flows/$flowId'
      path: '/$flowId'
      fullPath: '/dashboard/$organizationSlug/flows/$flowId'
      preLoaderRoute: typeof DashboardOrganizationSlugFlowsFlowIdRouteImport
      parentRoute: typeof DashboardOrganizationSlugFlowsRoute
    }
    '/dashboard/$organizationSlug/devices/$id': {
      id: '/dashboard/$organizationSlug/devices/$id'
      path: '/$id'
      fullPath: '/dashboard/$organizationSlug/devices/$id'
      preLoaderRoute: typeof DashboardOrganizationSlugDevicesIdRouteImport
      parentRoute: typeof DashboardOrganizationSlugDevicesRoute
    }
    '/dashboard/$organizationSlug/flows/$flowId/sessions': {
      id: '/dashboard/$organizationSlug/flows/$flowId/sessions'
      path: '/sessions'
      fullPath: '/dashboard/$organizationSlug/flows/$flowId/sessions'
      preLoaderRoute: typeof DashboardOrganizationSlugFlowsFlowIdSessionsRouteImport
      parentRoute: typeof DashboardOrganizationSlugFlowsFlowIdRoute
    }
    '/dashboard/$organizationSlug/flows/$flowId/logs': {
      id: '/dashboard/$organizationSlug/flows/$flowId/logs'
      path: '/logs'
      fullPath: '/dashboard/$organizationSlug/flows/$flowId/logs'
      preLoaderRoute: typeof DashboardOrganizationSlugFlowsFlowIdLogsRouteImport
      parentRoute: typeof DashboardOrganizationSlugFlowsFlowIdRoute
    }
  }
}

interface DashboardOrganizationSlugDevicesRouteChildren {
  DashboardOrganizationSlugDevicesIdRoute: typeof DashboardOrganizationSlugDevicesIdRoute
}

const DashboardOrganizationSlugDevicesRouteChildren: DashboardOrganizationSlugDevicesRouteChildren =
  {
    DashboardOrganizationSlugDevicesIdRoute:
      DashboardOrganizationSlugDevicesIdRoute,
  }

const DashboardOrganizationSlugDevicesRouteWithChildren =
  DashboardOrganizationSlugDevicesRoute._addFileChildren(
    DashboardOrganizationSlugDevicesRouteChildren,
  )

interface DashboardOrganizationSlugFlowsFlowIdRouteChildren {
  DashboardOrganizationSlugFlowsFlowIdLogsRoute: typeof DashboardOrganizationSlugFlowsFlowIdLogsRoute
  DashboardOrganizationSlugFlowsFlowIdSessionsRoute: typeof DashboardOrganizationSlugFlowsFlowIdSessionsRoute
}

const DashboardOrganizationSlugFlowsFlowIdRouteChildren: DashboardOrganizationSlugFlowsFlowIdRouteChildren =
  {
    DashboardOrganizationSlugFlowsFlowIdLogsRoute:
      DashboardOrganizationSlugFlowsFlowIdLogsRoute,
    DashboardOrganizationSlugFlowsFlowIdSessionsRoute:
      DashboardOrganizationSlugFlowsFlowIdSessionsRoute,
  }

const DashboardOrganizationSlugFlowsFlowIdRouteWithChildren =
  DashboardOrganizationSlugFlowsFlowIdRoute._addFileChildren(
    DashboardOrganizationSlugFlowsFlowIdRouteChildren,
  )

interface DashboardOrganizationSlugFlowsRouteChildren {
  DashboardOrganizationSlugFlowsFlowIdRoute: typeof DashboardOrganizationSlugFlowsFlowIdRouteWithChildren
  DashboardOrganizationSlugFlowsNewRoute: typeof DashboardOrganizationSlugFlowsNewRoute
  DashboardOrganizationSlugFlowsIndexRoute: typeof DashboardOrganizationSlugFlowsIndexRoute
}

const DashboardOrganizationSlugFlowsRouteChildren: DashboardOrganizationSlugFlowsRouteChildren =
  {
    DashboardOrganizationSlugFlowsFlowIdRoute:
      DashboardOrganizationSlugFlowsFlowIdRouteWithChildren,
    DashboardOrganizationSlugFlowsNewRoute:
      DashboardOrganizationSlugFlowsNewRoute,
    DashboardOrganizationSlugFlowsIndexRoute:
      DashboardOrganizationSlugFlowsIndexRoute,
  }

const DashboardOrganizationSlugFlowsRouteWithChildren =
  DashboardOrganizationSlugFlowsRoute._addFileChildren(
    DashboardOrganizationSlugFlowsRouteChildren,
  )

interface DashboardOrganizationSlugRouteChildren {
  DashboardOrganizationSlugAccountRoute: typeof DashboardOrganizationSlugAccountRoute
  DashboardOrganizationSlugAuditRoute: typeof DashboardOrganizationSlugAuditRoute
  DashboardOrganizationSlugContactsRoute: typeof DashboardOrganizationSlugContactsRoute
  DashboardOrganizationSlugDevicesRoute: typeof DashboardOrganizationSlugDevicesRouteWithChildren
  DashboardOrganizationSlugFlowsRoute: typeof DashboardOrganizationSlugFlowsRouteWithChildren
  DashboardOrganizationSlugGroupsRoute: typeof DashboardOrganizationSlugGroupsRoute
  DashboardOrganizationSlugInboxRoute: typeof DashboardOrganizationSlugInboxRoute
  DashboardOrganizationSlugLogsRoute: typeof DashboardOrganizationSlugLogsRoute
  DashboardOrganizationSlugNewslettersRoute: typeof DashboardOrganizationSlugNewslettersRoute
  DashboardOrganizationSlugRolesRoute: typeof DashboardOrganizationSlugRolesRoute
  DashboardOrganizationSlugSettingsRoute: typeof DashboardOrganizationSlugSettingsRoute
  DashboardOrganizationSlugUsersRoute: typeof DashboardOrganizationSlugUsersRoute
  DashboardOrganizationSlugWebhooksRoute: typeof DashboardOrganizationSlugWebhooksRoute
  DashboardOrganizationSlugIndexRoute: typeof DashboardOrganizationSlugIndexRoute
}

const DashboardOrganizationSlugRouteChildren: DashboardOrganizationSlugRouteChildren =
  {
    DashboardOrganizationSlugAccountRoute:
      DashboardOrganizationSlugAccountRoute,
    DashboardOrganizationSlugAuditRoute: DashboardOrganizationSlugAuditRoute,
    DashboardOrganizationSlugContactsRoute:
      DashboardOrganizationSlugContactsRoute,
    DashboardOrganizationSlugDevicesRoute:
      DashboardOrganizationSlugDevicesRouteWithChildren,
    DashboardOrganizationSlugFlowsRoute:
      DashboardOrganizationSlugFlowsRouteWithChildren,
    DashboardOrganizationSlugGroupsRoute: DashboardOrganizationSlugGroupsRoute,
    DashboardOrganizationSlugInboxRoute: DashboardOrganizationSlugInboxRoute,
    DashboardOrganizationSlugLogsRoute: DashboardOrganizationSlugLogsRoute,
    DashboardOrganizationSlugNewslettersRoute:
      DashboardOrganizationSlugNewslettersRoute,
    DashboardOrganizationSlugRolesRoute: DashboardOrganizationSlugRolesRoute,
    DashboardOrganizationSlugSettingsRoute:
      DashboardOrganizationSlugSettingsRoute,
    DashboardOrganizationSlugUsersRoute: DashboardOrganizationSlugUsersRoute,
    DashboardOrganizationSlugWebhooksRoute:
      DashboardOrganizationSlugWebhooksRoute,
    DashboardOrganizationSlugIndexRoute: DashboardOrganizationSlugIndexRoute,
  }

const DashboardOrganizationSlugRouteWithChildren =
  DashboardOrganizationSlugRoute._addFileChildren(
    DashboardOrganizationSlugRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardOrganizationSlugRoute: typeof DashboardOrganizationSlugRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOrganizationSlugRoute: DashboardOrganizationSlugRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
