/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardFlowsRouteImport } from './routes/dashboard.flows'
import { Route as DashboardDevicesRouteImport } from './routes/dashboard.devices'
import { Route as DashboardFlowsIndexRouteImport } from './routes/dashboard.flows.index'
import { Route as DashboardFlowsNewRouteImport } from './routes/dashboard.flows.new'
import { Route as DashboardFlowsFlowIdRouteImport } from './routes/dashboard.flows.$flowId'
import { Route as DashboardDevicesIdRouteImport } from './routes/dashboard.devices.$id'
import { Route as DashboardFlowsFlowIdLogsRouteImport } from './routes/dashboard.flows.$flowId.logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlowsRoute = DashboardFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlowsIndexRoute = DashboardFlowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFlowsRoute,
} as any)
const DashboardFlowsNewRoute = DashboardFlowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardFlowsRoute,
} as any)
const DashboardFlowsFlowIdRoute = DashboardFlowsFlowIdRouteImport.update({
  id: '/$flowId',
  path: '/$flowId',
  getParentRoute: () => DashboardFlowsRoute,
} as any)
const DashboardDevicesIdRoute = DashboardDevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardDevicesRoute,
} as any)
const DashboardFlowsFlowIdLogsRoute =
  DashboardFlowsFlowIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DashboardFlowsFlowIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/flows': typeof DashboardFlowsRouteWithChildren
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/devices/$id': typeof DashboardDevicesIdRoute
  '/dashboard/flows/$flowId': typeof DashboardFlowsFlowIdRouteWithChildren
  '/dashboard/flows/new': typeof DashboardFlowsNewRoute
  '/dashboard/flows/': typeof DashboardFlowsIndexRoute
  '/dashboard/flows/$flowId/logs': typeof DashboardFlowsFlowIdLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/devices/$id': typeof DashboardDevicesIdRoute
  '/dashboard/flows/$flowId': typeof DashboardFlowsFlowIdRouteWithChildren
  '/dashboard/flows/new': typeof DashboardFlowsNewRoute
  '/dashboard/flows': typeof DashboardFlowsIndexRoute
  '/dashboard/flows/$flowId/logs': typeof DashboardFlowsFlowIdLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/flows': typeof DashboardFlowsRouteWithChildren
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/devices/$id': typeof DashboardDevicesIdRoute
  '/dashboard/flows/$flowId': typeof DashboardFlowsFlowIdRouteWithChildren
  '/dashboard/flows/new': typeof DashboardFlowsNewRoute
  '/dashboard/flows/': typeof DashboardFlowsIndexRoute
  '/dashboard/flows/$flowId/logs': typeof DashboardFlowsFlowIdLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/devices'
    | '/dashboard/flows'
    | '/dashboard/inbox'
    | '/dashboard/logs'
    | '/dashboard/'
    | '/dashboard/devices/$id'
    | '/dashboard/flows/$flowId'
    | '/dashboard/flows/new'
    | '/dashboard/flows/'
    | '/dashboard/flows/$flowId/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/devices'
    | '/dashboard/inbox'
    | '/dashboard/logs'
    | '/dashboard'
    | '/dashboard/devices/$id'
    | '/dashboard/flows/$flowId'
    | '/dashboard/flows/new'
    | '/dashboard/flows'
    | '/dashboard/flows/$flowId/logs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/devices'
    | '/dashboard/flows'
    | '/dashboard/inbox'
    | '/dashboard/logs'
    | '/dashboard/'
    | '/dashboard/devices/$id'
    | '/dashboard/flows/$flowId'
    | '/dashboard/flows/new'
    | '/dashboard/flows/'
    | '/dashboard/flows/$flowId/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flows': {
      id: '/dashboard/flows'
      path: '/flows'
      fullPath: '/dashboard/flows'
      preLoaderRoute: typeof DashboardFlowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devices': {
      id: '/dashboard/devices'
      path: '/devices'
      fullPath: '/dashboard/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flows/': {
      id: '/dashboard/flows/'
      path: '/'
      fullPath: '/dashboard/flows/'
      preLoaderRoute: typeof DashboardFlowsIndexRouteImport
      parentRoute: typeof DashboardFlowsRoute
    }
    '/dashboard/flows/new': {
      id: '/dashboard/flows/new'
      path: '/new'
      fullPath: '/dashboard/flows/new'
      preLoaderRoute: typeof DashboardFlowsNewRouteImport
      parentRoute: typeof DashboardFlowsRoute
    }
    '/dashboard/flows/$flowId': {
      id: '/dashboard/flows/$flowId'
      path: '/$flowId'
      fullPath: '/dashboard/flows/$flowId'
      preLoaderRoute: typeof DashboardFlowsFlowIdRouteImport
      parentRoute: typeof DashboardFlowsRoute
    }
    '/dashboard/devices/$id': {
      id: '/dashboard/devices/$id'
      path: '/$id'
      fullPath: '/dashboard/devices/$id'
      preLoaderRoute: typeof DashboardDevicesIdRouteImport
      parentRoute: typeof DashboardDevicesRoute
    }
    '/dashboard/flows/$flowId/logs': {
      id: '/dashboard/flows/$flowId/logs'
      path: '/logs'
      fullPath: '/dashboard/flows/$flowId/logs'
      preLoaderRoute: typeof DashboardFlowsFlowIdLogsRouteImport
      parentRoute: typeof DashboardFlowsFlowIdRoute
    }
  }
}

interface DashboardDevicesRouteChildren {
  DashboardDevicesIdRoute: typeof DashboardDevicesIdRoute
}

const DashboardDevicesRouteChildren: DashboardDevicesRouteChildren = {
  DashboardDevicesIdRoute: DashboardDevicesIdRoute,
}

const DashboardDevicesRouteWithChildren =
  DashboardDevicesRoute._addFileChildren(DashboardDevicesRouteChildren)

interface DashboardFlowsFlowIdRouteChildren {
  DashboardFlowsFlowIdLogsRoute: typeof DashboardFlowsFlowIdLogsRoute
}

const DashboardFlowsFlowIdRouteChildren: DashboardFlowsFlowIdRouteChildren = {
  DashboardFlowsFlowIdLogsRoute: DashboardFlowsFlowIdLogsRoute,
}

const DashboardFlowsFlowIdRouteWithChildren =
  DashboardFlowsFlowIdRoute._addFileChildren(DashboardFlowsFlowIdRouteChildren)

interface DashboardFlowsRouteChildren {
  DashboardFlowsFlowIdRoute: typeof DashboardFlowsFlowIdRouteWithChildren
  DashboardFlowsNewRoute: typeof DashboardFlowsNewRoute
  DashboardFlowsIndexRoute: typeof DashboardFlowsIndexRoute
}

const DashboardFlowsRouteChildren: DashboardFlowsRouteChildren = {
  DashboardFlowsFlowIdRoute: DashboardFlowsFlowIdRouteWithChildren,
  DashboardFlowsNewRoute: DashboardFlowsNewRoute,
  DashboardFlowsIndexRoute: DashboardFlowsIndexRoute,
}

const DashboardFlowsRouteWithChildren = DashboardFlowsRoute._addFileChildren(
  DashboardFlowsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardDevicesRoute: typeof DashboardDevicesRouteWithChildren
  DashboardFlowsRoute: typeof DashboardFlowsRouteWithChildren
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDevicesRoute: DashboardDevicesRouteWithChildren,
  DashboardFlowsRoute: DashboardFlowsRouteWithChildren,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
