/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard.webhooks'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRolesRouteImport } from './routes/dashboard.roles'
import { Route as DashboardNewslettersRouteImport } from './routes/dashboard.newsletters'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardGroupsRouteImport } from './routes/dashboard.groups'
import { Route as DashboardFlowsRouteImport } from './routes/dashboard.flows'
import { Route as DashboardDevicesRouteImport } from './routes/dashboard.devices'
import { Route as DashboardContactsRouteImport } from './routes/dashboard.contacts'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardFlowsIndexRouteImport } from './routes/dashboard.flows.index'
import { Route as DashboardFlowsNewRouteImport } from './routes/dashboard.flows.new'
import { Route as DashboardFlowsFlowIdRouteImport } from './routes/dashboard.flows.$flowId'
import { Route as DashboardDevicesIdRouteImport } from './routes/dashboard.devices.$id'
import { Route as DashboardFlowsFlowIdSessionsRouteImport } from './routes/dashboard.flows.$flowId.sessions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewslettersRoute = DashboardNewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsRoute = DashboardGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlowsRoute = DashboardFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlowsIndexRoute = DashboardFlowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFlowsRoute,
} as any)
const DashboardFlowsNewRoute = DashboardFlowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardFlowsRoute,
} as any)
const DashboardFlowsFlowIdRoute = DashboardFlowsFlowIdRouteImport.update({
  id: '/$flowId',
  path: '/$flowId',
  getParentRoute: () => DashboardFlowsRoute,
} as any)
const DashboardDevicesIdRoute = DashboardDevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardDevicesRoute,
} as any)
const DashboardFlowsFlowIdSessionsRoute =
  DashboardFlowsFlowIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => DashboardFlowsFlowIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/flows': typeof DashboardFlowsRouteWithChildren
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/newsletters': typeof DashboardNewslettersRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/devices/$id': typeof DashboardDevicesIdRoute
  '/dashboard/flows/$flowId': typeof DashboardFlowsFlowIdRouteWithChildren
  '/dashboard/flows/new': typeof DashboardFlowsNewRoute
  '/dashboard/flows/': typeof DashboardFlowsIndexRoute
  '/dashboard/flows/$flowId/sessions': typeof DashboardFlowsFlowIdSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/newsletters': typeof DashboardNewslettersRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/devices/$id': typeof DashboardDevicesIdRoute
  '/dashboard/flows/$flowId': typeof DashboardFlowsFlowIdRouteWithChildren
  '/dashboard/flows/new': typeof DashboardFlowsNewRoute
  '/dashboard/flows': typeof DashboardFlowsIndexRoute
  '/dashboard/flows/$flowId/sessions': typeof DashboardFlowsFlowIdSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/flows': typeof DashboardFlowsRouteWithChildren
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/newsletters': typeof DashboardNewslettersRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/devices/$id': typeof DashboardDevicesIdRoute
  '/dashboard/flows/$flowId': typeof DashboardFlowsFlowIdRouteWithChildren
  '/dashboard/flows/new': typeof DashboardFlowsNewRoute
  '/dashboard/flows/': typeof DashboardFlowsIndexRoute
  '/dashboard/flows/$flowId/sessions': typeof DashboardFlowsFlowIdSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/account'
    | '/dashboard/audit'
    | '/dashboard/contacts'
    | '/dashboard/devices'
    | '/dashboard/flows'
    | '/dashboard/groups'
    | '/dashboard/inbox'
    | '/dashboard/newsletters'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/webhooks'
    | '/dashboard/'
    | '/dashboard/devices/$id'
    | '/dashboard/flows/$flowId'
    | '/dashboard/flows/new'
    | '/dashboard/flows/'
    | '/dashboard/flows/$flowId/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/account'
    | '/dashboard/audit'
    | '/dashboard/contacts'
    | '/dashboard/devices'
    | '/dashboard/groups'
    | '/dashboard/inbox'
    | '/dashboard/newsletters'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/webhooks'
    | '/dashboard'
    | '/dashboard/devices/$id'
    | '/dashboard/flows/$flowId'
    | '/dashboard/flows/new'
    | '/dashboard/flows'
    | '/dashboard/flows/$flowId/sessions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/account'
    | '/dashboard/audit'
    | '/dashboard/contacts'
    | '/dashboard/devices'
    | '/dashboard/flows'
    | '/dashboard/groups'
    | '/dashboard/inbox'
    | '/dashboard/newsletters'
    | '/dashboard/roles'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/webhooks'
    | '/dashboard/'
    | '/dashboard/devices/$id'
    | '/dashboard/flows/$flowId'
    | '/dashboard/flows/new'
    | '/dashboard/flows/'
    | '/dashboard/flows/$flowId/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/newsletters': {
      id: '/dashboard/newsletters'
      path: '/newsletters'
      fullPath: '/dashboard/newsletters'
      preLoaderRoute: typeof DashboardNewslettersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups': {
      id: '/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof DashboardGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flows': {
      id: '/dashboard/flows'
      path: '/flows'
      fullPath: '/dashboard/flows'
      preLoaderRoute: typeof DashboardFlowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devices': {
      id: '/dashboard/devices'
      path: '/devices'
      fullPath: '/dashboard/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flows/': {
      id: '/dashboard/flows/'
      path: '/'
      fullPath: '/dashboard/flows/'
      preLoaderRoute: typeof DashboardFlowsIndexRouteImport
      parentRoute: typeof DashboardFlowsRoute
    }
    '/dashboard/flows/new': {
      id: '/dashboard/flows/new'
      path: '/new'
      fullPath: '/dashboard/flows/new'
      preLoaderRoute: typeof DashboardFlowsNewRouteImport
      parentRoute: typeof DashboardFlowsRoute
    }
    '/dashboard/flows/$flowId': {
      id: '/dashboard/flows/$flowId'
      path: '/$flowId'
      fullPath: '/dashboard/flows/$flowId'
      preLoaderRoute: typeof DashboardFlowsFlowIdRouteImport
      parentRoute: typeof DashboardFlowsRoute
    }
    '/dashboard/devices/$id': {
      id: '/dashboard/devices/$id'
      path: '/$id'
      fullPath: '/dashboard/devices/$id'
      preLoaderRoute: typeof DashboardDevicesIdRouteImport
      parentRoute: typeof DashboardDevicesRoute
    }
    '/dashboard/flows/$flowId/sessions': {
      id: '/dashboard/flows/$flowId/sessions'
      path: '/sessions'
      fullPath: '/dashboard/flows/$flowId/sessions'
      preLoaderRoute: typeof DashboardFlowsFlowIdSessionsRouteImport
      parentRoute: typeof DashboardFlowsFlowIdRoute
    }
  }
}

interface DashboardDevicesRouteChildren {
  DashboardDevicesIdRoute: typeof DashboardDevicesIdRoute
}

const DashboardDevicesRouteChildren: DashboardDevicesRouteChildren = {
  DashboardDevicesIdRoute: DashboardDevicesIdRoute,
}

const DashboardDevicesRouteWithChildren =
  DashboardDevicesRoute._addFileChildren(DashboardDevicesRouteChildren)

interface DashboardFlowsFlowIdRouteChildren {
  DashboardFlowsFlowIdSessionsRoute: typeof DashboardFlowsFlowIdSessionsRoute
}

const DashboardFlowsFlowIdRouteChildren: DashboardFlowsFlowIdRouteChildren = {
  DashboardFlowsFlowIdSessionsRoute: DashboardFlowsFlowIdSessionsRoute,
}

const DashboardFlowsFlowIdRouteWithChildren =
  DashboardFlowsFlowIdRoute._addFileChildren(DashboardFlowsFlowIdRouteChildren)

interface DashboardFlowsRouteChildren {
  DashboardFlowsFlowIdRoute: typeof DashboardFlowsFlowIdRouteWithChildren
  DashboardFlowsNewRoute: typeof DashboardFlowsNewRoute
  DashboardFlowsIndexRoute: typeof DashboardFlowsIndexRoute
}

const DashboardFlowsRouteChildren: DashboardFlowsRouteChildren = {
  DashboardFlowsFlowIdRoute: DashboardFlowsFlowIdRouteWithChildren,
  DashboardFlowsNewRoute: DashboardFlowsNewRoute,
  DashboardFlowsIndexRoute: DashboardFlowsIndexRoute,
}

const DashboardFlowsRouteWithChildren = DashboardFlowsRoute._addFileChildren(
  DashboardFlowsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardDevicesRoute: typeof DashboardDevicesRouteWithChildren
  DashboardFlowsRoute: typeof DashboardFlowsRouteWithChildren
  DashboardGroupsRoute: typeof DashboardGroupsRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardNewslettersRoute: typeof DashboardNewslettersRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardDevicesRoute: DashboardDevicesRouteWithChildren,
  DashboardFlowsRoute: DashboardFlowsRouteWithChildren,
  DashboardGroupsRoute: DashboardGroupsRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardNewslettersRoute: DashboardNewslettersRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
